version: "3"

services: 
  control_server:
    image: ghcr.io/peterdavidfagan/lite6_control:rolling
    network_mode: "host"
    build: 
      context: ../../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_control_demos control_server.launch.py # replace with command for specific tutorial

  servo:
    image: ghcr.io/peterdavidfagan/lite6_control:rolling
    network_mode: "host"
    build: 
      context: ../../../
      dockerfile: .docker/control/Dockerfile.control
    devices:
      - "/dev:/dev"
    privileged: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 70
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
    command: ros2 launch lite6_control_demos servo_pose_jtc.launch.py # replace with command for specific tutorial

